### ISSUE TITLE
[Question]How can I convert int128 to byte[]

### ISSUE THREAD

**Issue by molto0504** [shabbyrobe/go-num#1]
Thanks for your library, it is really helpful.

I can't find a way to conver i128 to byte[]. Is there some function like 'GetBytes' can accomplish it?

**Comment by molto0504** [comment]
How about add some method like this(does not test):

```
func (i *I128) GetBytesBIgEndian() []byte {
	buf := make([]byte, 16)
        binary.BigEndian.PutUint64(buf[8:], i.lo)
	binary.BigEndian.PutUint64(buf[8:], i.hi)
	return buf
}
func (i *I128) GetBytesLittleEndian() []byte {
	buf := make([]byte, 16)
        binary.LittleEndian.PutUint64(buf[8:], i.hi)
	binary.LittleEndian.PutUint64(buf[8:], i.lo)
	return buf
}
```

It may convenient sometimes.

**Comment by shabbyrobe** [comment]
This is a good suggestion, it's definitely a gap. I think I have a solution, I should push a branch up some time this weekend. Please feel free to give me a ping any time if it falls off my radar.

**Comment by shabbyrobe** [comment]
I've added this now, thanks for the suggestion.

```go
{ // Big-endian
    b := make([]byte, 16)
    num.U128From64(1).PutBigEndian(b)
    u := num.MustU128FromBigEndian(b)
    fmt.Println(u)
}

{ // Little-endian
    b := make([]byte, 16)
    num.U128From64(1).PutLittleEndian(b)
    u := num.MustU128FromLittleEndian(b)
    fmt.Println(u)
}
```

The methods have been added to U128 only; this is to match how `encoding.Binary` works. Convert an I128 to a U128 first to get the bytes:

```go
b := make([]byte, 16)
num.I128From64(1).AsU128().PutBigEndian(b)
```

**Comment by molto0504** [comment]
Elegant code, that's exactly what I need, thx. 🙏
